name: 'Lock Threads'

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    if: github.repository_owner == 'psf'
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@e460dfeb36e731f3aeb214be6b0c9a9d9a67eda6 # v3.0.0
        with:
            issue-lock-inactive-days: 90
            pr-lock-inactive-days: 90
